package GUI;

import Database.DatabaseConnection;
import Gudang.ElektronikClass;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


public class ShowMenu extends javax.swing.JFrame {
    private DatabaseConnection db;

public void displayElectronics() {
    
    DefaultTableModel model = (DefaultTableModel) tblElektronik.getModel();
    model.setRowCount(0); // Mengosongkan tabel
    model.setColumnIdentifiers(new Object[]{"ID Barang ", "Model", "Merk"});

    try {
        db.getConnection(); // Buka koneksi database

        // Gunakan objek statement yang sudah ada
        db.statement = db.connection.createStatement();

        String query = "SELECT * FROM elektronik";
        ResultSet resultSet = db.statement.executeQuery(query);

        while (resultSet.next()) {
            int id = resultSet.getInt("id_barang");
            String modelName = resultSet.getString("model");
            String merk = resultSet.getString("merk");

            model.addRow(new Object[]{id, modelName, merk});
        }

        resultSet.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle exceptions
    } finally {
        db.disconnected(); // Tutup koneksi setelah selesai
    }
}





    
    
   
    
  
    public ShowMenu() {
        initComponents();
        db = new DatabaseConnection(); // Inisialisasi objek Database
        db.getConnection(); // Buka koneksi database
        displayElectronics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tblElektronik = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblElektronik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblElektronik);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 590, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblElektronik;
    // End of variables declaration//GEN-END:variables
}
