package GUI;

import Database.DatabaseConnection;
import Gudang.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;

public class Elektronik extends javax.swing.JFrame {
    int xx, xy;
    private Statement statement;
        public void close() {
        WindowEvent closewindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closewindow);
    }

       
        
private boolean isIdDuplicate(int id, String tableName) {
    DatabaseConnection db = null; 
    try {
        db = new DatabaseConnection();
        Connection connection = db.getConnection();
        statement = connection.createStatement();

        String query = "SELECT * FROM " + tableName + " WHERE id_barang = " + id;
        ResultSet resultSet = statement.executeQuery(query);

        return resultSet.next(); 

    } catch (SQLException ex) {
        ex.printStackTrace();
        
    } finally {
        if (db != null) {
            db.disconnected();
        }
    }

    return false;
}        
        
        
        
        
        
        
    public Elektronik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdBarang = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtMerk = new javax.swing.JTextField();
        txtDeskripsi = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        txtJumlahBarang = new javax.swing.JTextField();
        btncreate = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblKaryawanID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdBarang.setBorder(null);
        getContentPane().add(txtIdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 220, 30));

        txtModel.setBorder(null);
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });
        getContentPane().add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 220, 30));

        txtMerk.setBorder(null);
        getContentPane().add(txtMerk, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 220, 30));

        txtDeskripsi.setBorder(null);
        getContentPane().add(txtDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 220, 30));

        txtNamaBarang.setBorder(null);
        getContentPane().add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 220, 30));

        txtJumlahBarang.setBorder(null);
        txtJumlahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahBarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtJumlahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 220, 30));

        btncreate.setText("Create");
        btncreate.setBorder(null);
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        getContentPane().add(btncreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 110, 40));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrowww.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/6.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        lblKaryawanID.setText("jLabel2");
        getContentPane().add(lblKaryawanID, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtJumlahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahBarangActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
    
    String idBarangText = txtIdBarang.getText().trim();
    String namaBarang = txtNamaBarang.getText().trim();
    String deskripsi = txtDeskripsi.getText().trim();
    String jumlahBarangText = txtJumlahBarang.getText().trim();

        
    if (idBarangText.isEmpty() || namaBarang.isEmpty() || deskripsi.isEmpty() || jumlahBarangText.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Semua field harus diisi.");
        return;
    }
    
        
    if (!idBarangText.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "ID barang harus berupa angka.");
        return;
    }
    
    
    int idBarang = Integer.parseInt(idBarangText);
    int jumlahBarang = Integer.parseInt(jumlahBarangText);
    
    
        
    if (idBarang < 1) {
        JOptionPane.showMessageDialog(null, "ID barang tidak boleh negatif.");
        return;
    }
    
        
    if (jumlahBarang < 1) {
        JOptionPane.showMessageDialog(null, "Jumlah barang tidak boleh kurang dari 1.");
        return;
    }
    
    
    if (isIdDuplicate(idBarang, "barang")) {
        JOptionPane.showMessageDialog(null, "ID barang sudah digunakan. Tolong gunakan ID lain.");
        return;
    }

    
    BarangClass barang = new BarangClass();
    barang.setIdBarang(idBarang);
    barang.setNamaBarang(namaBarang);
    barang.setDeskripsi(deskripsi);
    barang.setJumlahBarang(jumlahBarang);
    barang.setKaryawanID(lblKaryawanID.getText());

    // Panggil metode createBarang
    if (barang.createBarang()) {
        JOptionPane.showMessageDialog(null, "Data barang berhasil disimpan.");
    } else {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan data barang.");
    }

    // Baca nilai dari teks field untuk tabel elektronik
    int idElektronik = Integer.parseInt(txtIdBarang.getText());
    String model = txtModel.getText();
    String merk = txtMerk.getText();

    // Buat objek ElektronikClass dan isi atributnya
    ElektronikClass elektronik = new ElektronikClass();
    elektronik.setIdBarang(idElektronik);
    elektronik.setModel(model);
    elektronik.setMerk(merk);

    // Panggil metode createElektronik
    if (elektronik.createElektronik()) {
        JOptionPane.showMessageDialog(null, "Data elektronik berhasil disimpan.");
    } else {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan data elektronik.");
    }
    
    // Buat objek DataBarang dan isi atributnya
    DataBarangClass dataBarang = new DataBarangClass();
    dataBarang.setIdBarang(String.valueOf(idBarang));
    dataBarang.setJumlahBarang(String.valueOf(jumlahBarang));
    
    // Panggil metode createDataBarang
    if (dataBarang.createDataBarang()) {
        JOptionPane.showMessageDialog(null, "Data Barang Masuk berhasil disimpan.");
    } else {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan data barang masuk.");
    }

    }//GEN-LAST:event_btncreateActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        close();
        SelectCategory mm = new SelectCategory();
        mm.lblKaryawanID.setText(lblKaryawanID.getText());
        mm.setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // get KaryawanID
    
    System.out.println("=========== KARYAWAN ID : " + lblKaryawanID.getText());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elektronik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elektronik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elektronik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elektronik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elektronik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton btncreate;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblKaryawanID;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtJumlahBarang;
    private javax.swing.JTextField txtMerk;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtNamaBarang;
    // End of variables declaration//GEN-END:variables
}
