package GUI;

import Database.DatabaseConnection;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.table.DefaultTableModel;



public class ShowMenu extends javax.swing.JFrame {
    int xx, xy;
    public void close() {
        WindowEvent closewindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closewindow);
    }
    
    
    
    
//    private DatabaseConnection db;
//
//public void displayElektronik() {
//    
//    DefaultTableModel model = (DefaultTableModel) tblElektronik.getModel();
//    model.setRowCount(0); // Mengosongkan tabel
//    model.setColumnIdentifiers(new Object[]{"ID Barang ", "Model", "Merk"});
//
//    try {
//        db.getConnection(); // Buka koneksi database
//
//        // Gunakan objek statement yang sudah ada
//        db.statement = db.connection.createStatement();
//
//        String query = "SELECT * FROM elektronik";
//        ResultSet resultSet = db.statement.executeQuery(query);
//
//        while (resultSet.next()) {
//            int id = resultSet.getInt("id_barang");
//            String modelName = resultSet.getString("model");
//            String merk = resultSet.getString("merk");
//
//            model.addRow(new Object[]{id, modelName, merk});
//        }
//
//        resultSet.close();
//    } catch (SQLException ex) {
//        ex.printStackTrace();
//        // Handle exceptions
//    } finally {
//        db.disconnected(); // Tutup koneksi setelah selesai
//    }
//}
//
//public void displayMakanan() {
//    
//    DefaultTableModel model = (DefaultTableModel) tblMakanan.getModel();
//    model.setRowCount(0); // Mengosongkan tabel
//    model.setColumnIdentifiers(new Object[]{"ID Barang ", "Tanggal Kadaluarsa", "Jenis Makanan"});
//
//    try {
//        db.getConnection(); // Buka koneksi database
//
//        // Gunakan objek statement yang sudah ada
//        db.statement = db.connection.createStatement();
//
//        String query = "SELECT * FROM makanan";
//        ResultSet resultSet = db.statement.executeQuery(query);
//
//        while (resultSet.next()) {
//            int id = resultSet.getInt("id_barang");
//            String tgl_kadaluarsa = resultSet.getString("tanggal_kadaluarsa");
//            String jenis_makanan = resultSet.getString("jenis_makanan");
//
//            model.addRow(new Object[]{id, tgl_kadaluarsa, jenis_makanan});
//        }
//
//        resultSet.close();
//    } catch (SQLException ex) {
//        ex.printStackTrace();
//        // Handle exceptions
//    } finally {
//        db.disconnected(); // Tutup koneksi setelah selesai
//    }
//}
//
//public void displayPakaian() {
//    
//    DefaultTableModel model = (DefaultTableModel) tblPakaian.getModel();
//    model.setRowCount(0); // Mengosongkan tabel
//    model.setColumnIdentifiers(new Object[]{"ID Barang ", "Ukuran", "Warna", "Bahan"});
//
//    try {
//        db.getConnection(); // Buka koneksi database
//
//        // Gunakan objek statement yang sudah ada
//        db.statement = db.connection.createStatement();
//
//        String query = "SELECT * FROM pakaian";
//        ResultSet resultSet = db.statement.executeQuery(query);
//
//        while (resultSet.next()) {
//            int id = resultSet.getInt("id_barang");
//            String ukuran = resultSet.getString("ukuran");
//            String warna = resultSet.getString("warna");
//            String bahan = resultSet.getString("bahan");
//
//            model.addRow(new Object[]{id, ukuran, warna, bahan});
//        }
//
//        resultSet.close();
//    } catch (SQLException ex) {
//        ex.printStackTrace();
//        // Handle exceptions
//    } finally {
//        db.disconnected(); // Tutup koneksi setelah selesai
//    }
//}

  
    public ShowMenu() {
        initComponents();
//        db = new DatabaseConnection(); // Inisialisasi objek Database
//        db.getConnection(); // Buka koneksi database
//        displayElektronik();
//        displayMakanan();
//        displayPakaian();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ele = new javax.swing.JLabel();
        pka = new javax.swing.JLabel();
        mkn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        masok = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eleMouseClicked(evt);
            }
        });
        getContentPane().add(ele, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 190, 130));

        pka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pkaMouseClicked(evt);
            }
        });
        getContentPane().add(pka, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 190, 130));

        mkn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mknMouseClicked(evt);
            }
        });
        getContentPane().add(mkn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 190, 130));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrowww.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 50, 50));

        masok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masokMouseClicked(evt);
            }
        });
        getContentPane().add(masok, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 190, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/showcate.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleMouseClicked
        close();
        ShowElektronik el = new ShowElektronik();
        el.setVisible(true);
    }//GEN-LAST:event_eleMouseClicked

    private void pkaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkaMouseClicked
        close();
        ShowPakaian el = new ShowPakaian();
        el.setVisible(true);
    }//GEN-LAST:event_pkaMouseClicked

    private void mknMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mknMouseClicked
        close();
        ShowMakanan el = new ShowMakanan();
        el.setVisible(true);
    }//GEN-LAST:event_mknMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        close();
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void masokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masokMouseClicked
        close();
        ShowDBM mm = new ShowDBM();
        mm.setVisible(true);
    }//GEN-LAST:event_masokMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ele;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel masok;
    private javax.swing.JLabel mkn;
    private javax.swing.JLabel pka;
    // End of variables declaration//GEN-END:variables
}
